language: node_js
node_js: 6

install:
  - yarn

script:
  - yarn test -- --coverage
  - yarn build

after_success:
  - yarn add codacy-coverage
  - $(npm bin)/codacy-coverage -v < ./coverage/lcov.info

cache:
  yarn: true
  directories:
    - node_modules
